berou/accounts/urls.py
from django.conf import settings
from django.conf.urls import url

from accounts import views

urlpatterns = [
    url(r'^$', views.RegisterUserView.as_view(), name='register_user'),
    url(r'^login/$',
        views.LoginUserView.as_view(),
        name='login_user'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': settings.LOGOUT_REDIRECT_URL},
        name='logout_user'),
    url(r'^profile/(?P<pk>\d+)$',
        views.ProfileView.as_view(),
        name='profile'),
    url(r'^edit_profile/(?P<pk>\d+)$',
        views.EditProfileView.as_view(),
        name='edit_profile'),
    url(r'^change_password/$',
        views.ChangePasswordView.as_view(),
        name='change_password'),
]

berou/application_system/urls.py
from django.conf.urls import url

from application_system import views

urlpatterns = [
    url(r'^$', views.ListAppView.as_view(), name='list_app'),
    url(r'^list_available_app/$',
        views.ListAvailableAppView.as_view(),
        name='list_available_app'),
    url(r'^install_app/$', views.InstallAppView.as_view(), name='install_app'),
    url(r'^uninstall_app/(?P<package>[\w-]+)/$',
        views.UninstallAppView.as_view(),
        name='uninstall_app'),
    url(r'activate_app/(?P<package>[\w-]+)/$',
        views.ActivateAppView.as_view(),
        name='activate_app'),
    url(r'disable_app/(?P<package>[\w-]+)/$',
        views.DisableAppView.as_view(),
        name='disable_app'),
]

berou/berou/urls.py
import importlib
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from accounts import urls as accounts_urls
from berou import berou_urls
from application_system import urls as application_system_urls
from application_system import models


def get_plugin_packages():
    return [app.package for app in models.App.objects.all()]


urlpatterns = [
    # Examples:
    # url(r'^$', 'berou.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include(accounts_urls, namespace='accounts')),
    url(r'^application_system/', include(application_system_urls,
                                         namespace='application_system')),
    url(r'^', include(berou_urls, namespace='berou')),
]

for plugin in get_plugin_packages():
    has_urls = True
    try:
        urls_module = importlib.import_module(plugin + '.urls')
    except ImportError:
        has_urls = False
    if has_urls:
        plugin_urls = url(
            r'^{plugin}/'.format(plugin=plugin),
            include(urls_module, namespace=plugin)
        )
        urlpatterns.append(plugin_urls)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

berou/berou/views.py
# -*- coding: utf-8 -*-

from django.core.urlresolvers import reverse
from django.shortcuts import redirect, render
from django.views.generic.list import ListView

from application_system import models
from berou import mixins


class ListAppView(mixins.OwnershipRequiredMixin, ListView):
    model = models.App.users.through

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            super(ListAppView, self).get(request, *args, **kwargs)
            return render(
                request,
                'berou/home.html',
                self.get_context_data(**kwargs)
            )
        return redirect(reverse('accounts:register_user'))

berou/berou/templates/berou/banner.html
{% load banner i18n %}
<ul class="nav navbar-nav">
    {% for app in list_app %}
        {% if request.path|path_startswith:app.slug %}
        <li class="active"><a href="/{{ app.slug }}">{% trans app.name %}<span class="sr-only">{% trans "(current)" %}</span></a></li>
        {% else %}
        <li><a href="/{{ app.slug }}">{% trans app.name %}</a></li>
        {% endif %}
    {% endfor %}
</ul>

berou/berou/templates/berou/base.html
{% load staticfiles form_helpers banner i18n %}
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" href="{% static 'bootstrap-3.3.4/css/bootstrap.css' %}">
<script src="{% static 'jquery-1.11.2/js/jquery.min.js' %}"></script>
<script src="{% static 'bootstrap-3.3.4/js/bootstrap.js' %}"></script>
<link rel="shortcut icon" type="image/x-pngicon" href="{% static 'berou/img/favicon.png' %}"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bérou</title>
</head>
<body>
<div id="wrap">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'berou:home' %}"><img class="logo" alt="Bérou" src="{% static 'berou/img/berou.svg' %}"></a>
            </div>

            {% if user.is_authenticated %}
            <div class="navbar-collapse">
                {% banner request user %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ user }} <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'accounts:profile' pk=user.id %}">{% trans "Profile" %}</a></li>
                        <li><a href="{% url 'application_system:list_available_app' %}">{% trans "My apps" %}</a></li>
                        <li role="presentation" class="divider"></li>
                        <li><a href="{% url 'accounts:logout_user' %}">{% trans "Logout" %}</a></li>
                    </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
            {% else %}
            <!-- TODO: use the actual login form -->
            <div class="navbar-form navbar-right">
                <form action="{% url 'accounts:login_user' %}?next={{ request.path }}" method="POST" class="form-inline">
                    {% csrf_token %}
                    {{ login_form.username|add_class:"form-control" }}
                    {{ login_form.password|add_class:"form-control" }}
                    <button type="submit" class="btn btn-default">Login</button>
                </form>
            </div>
            {% endif %}
        </div><!-- /.container-fluid -->
    </nav>
    <div class="container-fluid">
        <div class="row">
            {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-error" role="alert">{{ message }}</div>
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endif %}
            {% endfor %}
        </div>
        {% block content %}
        {% endblock content %}
    </div>
</div>
<footer id="footer" class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3>Bérou</h3>
                <ul>
                    <li><a href="/">Home</a></li>
                </ul>
            </div>
            <div class="col-md-6">
                <h3>Documentation</h3>
                <ul>
                    <li><a href="http://docs.berou.fr/">docs</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

berou/berou/templates/berou/home.html
{% extends 'berou/base.html' %}
{% load i18n partition %}
{% block content %}
{% if not user.is_authenticated %}
<a href="{% url 'accounts:login_user' %}">Login</a>
{% else %}
    {% if object_list %}
    {% for row_apps in object_list|partition:"3" %}
    <div class="row">
        {% for user_app in row_apps %}
        {% with app=user_app.app %}
        <div class="col-md-4">
            <a href="/{{ app.package }}/">
                <div class="media">
                    <div class="media-left">
                    {% if app.logo %}
                        <img class="img-thumbnail" src="{{ app.logo }}" alt="{{ app.name }}" />
                    {% endif %}
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">{% trans app.name %}</h4>
                        {% trans app.description %}
                        <div class="text-right">
                            <button class="btn btn-info">{% blocktrans with name=app.name %}Go to {{ name }}{% endblocktrans %}</button>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endwith %}
        {% endfor %}
    </div>
    {% endfor %}
    {% else %}
    {% trans "You don't have any enabled apps." %} <a href="{% url 'application_system:list_available_app' %}" class="btn btn-primary">{% trans "Activate your apps" %}</a>
    {% endif %}
{% endif %}
{% endblock content %}